### ISSUE TITLE
Installing from pip or setup.py gives error

### ISSUE THREAD

**Issue by graysonw** [pythonprofilers/memory_profiler#106]
Tested on both OS X 10.11 and Debian GNU/Linux 7. 

Collecting memory-profiler
  Downloading memory_profiler-0.38.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-BV2ywJ/memory-profiler/setup.py", line 1, in <module>
        import memory_profiler
      File "memory_profiler.py", line 863, in <module>
        magic_mprun = MemoryProfilerMagics().mprun.**func**
    TypeError: **init**() takes exactly 2 arguments (1 given)

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-BV2ywJ/memory-profiler

**Comment by korzeniewskipl** [comment]
@graysonw Which version of IPython you have installed?

**Comment by fabianp** [comment]
Thanks for the report @graysonw . I temporarily commented the offending lines (fdf9ef3) and updated the pypi version, please tell me whether this fixes the problem for you.

@korzeniewskipl : I would say we drop support for IPython < 1.0 to avoid these issues ([line_profiler](https://github.com/rkern/line_profiler/blob/master/line_profiler.py) after all only has the ```load_ipython_extension``` mechanism)

**Comment by Juanlu001** [comment]
This is probably not the case anymore.

**Comment by Juanlu001** [comment]
I'm closing this, feel free to reopen if the issue appears again.

**Comment by fabianp** [comment]
many thanks @Juanlu001 for going through these old issues!

**Comment by geofflangenderfer** [comment]
I'm also having this issue. Here's the output from the pip install command:

```
(test) geoff@ubuntu:~/work/Assignments/test$ pip install memory_profiler
Collecting memory_profiler
  Using cached https://files.pythonhosted.org/packages/9f/fe/1fca7273dd111108f204a686b12a12b6422d405fe4614087aa7d5a66ea87/memory_profiler-0.55.0.tar.gz
Collecting psutil (from memory_profiler)
  Using cached https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z5jap3d7/psutil/setup.py", line 350, in <module>
        main()
      File "/tmp/pip-install-z5jap3d7/psutil/setup.py", line 346, in main
        setup(**kwargs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z5jap3d7/psutil/
```
