### ISSUE TITLE
Syntax error in memory_profiler 0.45 on Python 2.6

### ISSUE THREAD

**Issue by jun66j5** [pythonprofilers/memory_profiler#137]
According to classifiers in `setup.py`, it seems memory-profiler still supports Python 2.6 but syntax error actually is raised.

```
   Using version 0.45 (newest of versions: 0.45, 0.44, 0.43, 0.42, 0.41, 0.40, 0.39, 0.38, 0.37, 0.36, 0.35, 0.34, 0.33, 0.32, 0.31, 0.30, 0.29, 0.28, 0.27, 0.26, 0.25, 0.24, 0.23, 0.22, 0.21, 0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.5, 0.4, 0.3, 0.2, 0.1)
   Using download cache from /arc/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fe9%2F16%2F135a03bb71126cb8f097bb2789fb0c46e297a801995f051318fdd49631e2%2Fmemory_profiler-0.45.tar.gz
   Running setup.py (path:/venv/py26/build/memory-profiler/setup.py) egg_info for package memory-profiler
     Traceback (most recent call last):
       File "<string>", line 17, in <module>
       File "/venv/py26/build/memory-profiler/setup.py", line 1, in <module>
         import memory_profiler
       File "memory_profiler.py", line 1080
         backends_indices = {b[0]: i for i, b in enumerate(all_backends)}
                                       ^
     SyntaxError: invalid syntax
```

**Comment by fabianp** [comment]
Thanks for the report. I would gladly take a patch fixing this, otherwise I’ll drop support for python2.6

**Comment by Juanlu001** [comment]
https://github.com/pythonprofilers/memory_profiler/pull/138 was merged so this probably can be closed.
