### ISSUE TITLE
mprof plot -o <image.out> on headless Alpine linux requires a display

### ISSUE THREAD

**Issue by cequencer** [pythonprofilers/memory_profiler#182]
According to the `mprof plot --help`:

>   --output OUTPUT, -o OUTPUT
>                       Save plot to file instead of displaying it.`

I want to use this option in a headless Alpine linux environment, as I do not have any X windows setup.  Is it correct to assume that using the `-o` option should bypass the need of X windows?

It seems to me that my assumption is incorrect:

>bash-4.3# mprof plot -o image.out
>Using last profile data.
>Traceback (most recent call last):
>  File "/usr/local/bin/mprof", line 551, in <module>
>    actions\[get_action()\]()
>  File "/usr/local/bin/mprof", line 507, in plot_action
>    fig = pl.figure(figsize=(14, 6), dpi=90)
>  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 539, in figure
>    **kwargs)
>  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
>    return cls.new_figure_manager_given_figure(num, fig)
>  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
>    window = Tk.Tk(className="matplotlib")
>  File "/usr/local/lib/python2.7/lib-tk/Tkinter.py", line 1819, in __init__
>    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
>_tkinter.TclError: no display name and no $DISPLAY environment variable`

Is it possible to avoid the display requirement so I can successfully output the image to a file?  
I understand there is temporary workaround such as SSH forwarding within a Docker image to satisfy the DISPLAY forwarding.  I would like to address it at the program level so this DISPLAY requirement will not be necessary if possible.  

It seems this is a well know issue and there ample ways to resolve it.  Here are some references that are not in any particular order:

Primary sources:
1. [matplotlib: backend](https://matplotlib.org/faq/usage_faq.html#what-is-a-backend)
1. [Anti-Grain Geometry project](http://antigrain.com/)

Known issues:
1. https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server
1. https://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined
1. https://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/

For reference, I am using Alpine linux from Dockerhub:

>bash-4.3# uname -a
>Linux 1bb6ad374b43 4.10.0-40-generic \#44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 Linux

Installing using `pip install memory_profiler`
...
>Collecting memory_profiler
>  Downloading memory_profiler-0.50.0.tar.gz
>Collecting matplotlib
>  Downloading matplotlib-2.1.1.tar.gz (36.1MB)
>Collecting psutil (from memory_profiler)
>  Downloading psutil-5.4.3.tar.gz (412kB)`
...

Thanks for looking into this.

**Comment by cequencer** [comment]
After I have done some researching, I have noticed an option that I did not pickup earlier:
`  --backend BACKEND     Specify the Matplotlib backend to use`

In conjunction with `-o`, this works as I assumed to be.  So the fault is on the user side for not knowing in advance about the backend option.  Now I have done the research, I learned how to use mprof plot properly for exactly this need.  Therefore I am closing this issue, but leaving this nugget in case someone out there runs into this same issue.  

Here is the resolution:
`$mprof plot -o image.png --backend agg`
`Using last profile data.`
