### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by SamuelXJames** [pythonprofilers/memory_profiler#210]
I am unable to run mprof plot. I get the above value error instead which is due to line 312 in mprof,py 
which is: field, value = l.split(' ', 1).

I am currently running memory_profiler as: python -m memory_profiler mprof plot <filename> in command. Mprof run works as intended.

**Comment by SamuelXJames** [comment]
Mprof is unable to parse white space, therefore blank lines need to deleted.

**Comment by Juanlu001** [comment]
> Mprof is unable to parse white space, therefore blank lines need to be deleted.

This is weird, could you please post a sample program so we can reproduce the issue?

**Comment by stepan-anokhin** [comment]
The problem occurs when `mprof run <command>` has multi-line arguments:

For example:
```bash
read -r -d '' MESSAGE << EOM            
  hello
  world
EOM

mprof run echo "$MESSAGE"
mprof plot
```
```
Using last profile data.
Traceback (most recent call last):
  File "/home/stepan/mprof-example/venv/bin/mprof", line 8, in <module>
    sys.exit(main())
  File "/home/stepan/mprof-example/venv/lib/python3.8/site-packages/mprof.py", line 905, in main
    actions[get_action()]()
  File "/home/stepan/mprof-example/venv/lib/python3.8/site-packages/mprof.py", line 819, in plot_action
    mprofile = plotter(filename, index=n, timestamps=timestamps, options=args)
  File "/home/stepan/mprof-example/venv/lib/python3.8/site-packages/mprof.py", line 409, in plot_file
    mprofile = read_mprofile_file(filename)
  File "/home/stepan/mprof-example/venv/lib/python3.8/site-packages/mprof.py", line 364, in read_mprofile_file
    field, value = l.split(' ', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
