### ISSUE TITLE
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-18sj9m6o/psutil/

### ISSUE THREAD

**Issue by geofflangenderfer** [pythonprofilers/memory_profiler#239]
I'm unable to install with pip. Here're the results of that command:

```
                                                                                                                                          
geoff@ubuntu:~/heapy_tutorial$ pip3 install memory_profiler                                                                                                             
Collecting memory_profiler
  Using cached https://files.pythonhosted.org/packages/9f/fe/1fca7273dd111108f204a686b12a12b6422d405fe4614087aa7d5a66ea87/memory_profiler-0.55.0.tar.gz
Collecting psutil (from memory_profiler)
  Using cached https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module> 
      File "/tmp/pip-install-18sj9m6o/psutil/setup.py", line 350, in <module>
        main()
      File "/tmp/pip-install-18sj9m6o/psutil/setup.py", line 346, in main
        setup(**kwargs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs) 
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-18sj9m6o/psutil/

```

**Comment by geofflangenderfer** [comment]
Interesting that the following command runs successfully:

```
(venv) geoff@ubuntu:~/work/Assignments/test$ python -c "from setuptools.dist import check_specifier"
(venv) geoff@ubuntu:~/work/Assignments/test$ 

```

**Comment by geofflangenderfer** [comment]
Need to downgrade setuptools: 

```
pip install setuptools==40.6.3
```
_Originally posted by @9antriksh in https://github.com/pypa/setuptools/issues/1654#issuecomment-458006241_
