### ISSUE TITLE
`TypeError: format() argument after * must be an iterable, not NoneType`

### ISSUE THREAD

**Issue by mikkokotila** [pythonprofilers/memory_profiler#240]
First, thanks a lot for an amazing package. It's really incredibly valuable. 

When I run my command: 

`mprof run ./test/performance/memory_pressure.py`

...everything completes fine and I can do `mprof plot` and have the `.dat` files with the data, but I get the following error message:

```
Traceback (most recent call last):
  File "/Users/mikko/miniconda3/envs/wip_conda/bin/mprof", line 11, in <module>
    sys.exit(main())
  File "/Users/mikko/miniconda3/envs/wip_conda/lib/python3.6/site-packages/mprof.py", line 592, in main
    actions[get_action()]()
  File "/Users/mikko/miniconda3/envs/wip_conda/lib/python3.6/site-packages/mprof.py", line 242, in run_action
    multiprocess=args.multiprocess, stream=f)
  File "/Users/mikko/miniconda3/envs/wip_conda/lib/python3.6/site-packages/memory_profiler.py", line 363, in memory_usage
    stream.write("MEM {0:.6f} {1:.4f}\n".format(*mem_usage))
TypeError: format() argument after * must be an iterable, not NoneType

```
While it seems merely a nuisance, it would be great to get rid of this. Any suggestions?

**Comment by raphaelvigee** [comment]
I can confirm this is still an issue

**Comment by Tioz90** [comment]
Still an issue

**Comment by fabianp** [comment]
Patches welcome :-)

**Comment by fabianp** [comment]
should be fixed in https://github.com/pythonprofilers/memory_profiler/commit/88f0aae4488328dc6d4f4750f48e35927dafb09b
