### ISSUE TITLE
mprof run should have an option to propagate the return code of the profiled script

### ISSUE THREAD

**Issue by arkal** [pythonprofilers/memory_profiler#303]
Hi,

I'm running memory-profiler 0.58.0 and I noticed that `mprof run` will return 0 even if the script it profiled has failed. I get that this *can be* desired behavior but I think it would be helpful to have a command line option to propagate the return code. 

I've reproduced the issue here in 2 different ways
Example 1: Segfault (I first noticed this issue when my jobs all segfaulted but return codes were ok)
```
Singularity> cat segfault.py
# This will segfault
# https://codegolf.stackexchange.com/a/216134
eval((lambda:0).__code__.replace(co_consts=()))

Singularity> python3.8 segfault.py 
Segmentation fault
Singularity> echo $?
139
Singularity> mprof run segfault.py 
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Singularity> echo $?
0
```

Example 2: Generic non-zero return code
```
Singularity> cat nonzero_return.py 
assert False

Singularity> python3.8 nonzero_return.py 
Traceback (most recent call last):
  File "nonzero_return.py", line 1, in <module>
    assert False
AssertionError
Singularity> echo $?
1
Singularity> mprof run nonzero_return.py 
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 1303, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 1204, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "nonzero_return.py", line 1, in <module>
    assert False
AssertionError
Singularity> echo $?
0
```

**Comment by arkal** [comment]
Bah 🤦 I was looking at the code and i realised you've already thought of this with the `-E` option. Sorry!
