### ISSUE TITLE
Import fails in Python3.11 with `ImportError: cannot import name 'coroutine' from 'asyncio'`

### ISSUE THREAD

**Issue by daanzu** [pythonprofilers/memory_profiler#364]
Was deprecated and is being removed in 3.11: https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine

```
  Traceback (most recent call last):
    File "/project/test_webrtcvad.py", line 5, in <module>
      from memory_profiler import memory_usage
    File "/tmp/tmp.EWDmnIKBET/venv/lib/python3.11/site-packages/memory_profiler.py", line 10, in <module>
      from asyncio import coroutine, iscoroutinefunction
  ImportError: cannot import name 'coroutine' from 'asyncio' (/opt/python/cp311-cp311/lib/python3.11/asyncio/__init__.py)
```

**Comment by fabianp** [comment]
thanks for the report. Would you be willing to submit a pull request fixing this issue?

**Comment by daanzu** [comment]
Since I can't easily test myself, I'll assume this is fixed, and close.
