### ISSUE TITLE
[BUG] invalid non-printable character U+FEFF

### ISSUE THREAD

**Issue by shenjackyuanjie** [pythonprofilers/memory_profiler#384]
I try to use memory profiler in my project, but it gives me this issue
```
shenjack  DR  ➜ (main  1)  ♥ 13:13  mprof.exe run DR.py
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\APPS\CPython\Python311\Lib\site-packages\memory_profiler.py", line 1351, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "D:\APPS\CPython\Python311\Lib\site-packages\memory_profiler.py", line 1252, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "DR.py", line 1
    ﻿"""
    ^
SyntaxError: invalid non-printable character U+FEFF
```
you can see the file in my [project](https://github.com/shenjackyuanjie/Difficult-Rocket/blob/242c2ca9a79f5089f74039e4b6b960b96d50fec7/DR.py)

##  Python info
- Version: `3.11.0`
- Branch: ``
- Implementation: `CPython`
- Compiler: `MSC v.1933 64 bit (AMD64)`

##  System info
- System: `Windows-10-10.0.19045-SP0`
- Computer name: `shenjack-5600X`
- machine: `AMD64`
- processor: `AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD`
- release: `10`
- version: `10.0.19045`

`Python info` and `System info` gen by [DR_crash_report](https://github.com/shenjackyuanjie/Difficult-Rocket/blob/242c2ca9a79f5089f74039e4b6b960b96d50fec7/Difficult_Rocket/crash/crash.py)

**Comment by shenjackyuanjie** [comment]
hmmmmm
thanks for anser!

**Comment by shenjackyuanjie** [comment]
well
is actully my? fault
![image](https://user-images.githubusercontent.com/54507071/219953428-5a2a5997-40a5-4048-9c4a-edf0ab2d2c7c.png)

**Comment by shenjackyuanjie** [comment]
maybe close this issue later

**Comment by altendky** [comment]
I think that it is triggered by your situation.  I don't think that makes it "your fault".  I also don't think that means there isn't anything to fix in this project.  I think we should make a change to allow for BOMs, and anything else Python allows such as the coding comments.  I just haven't made the time to do that.

**Comment by shenjackyuanjie** [comment]
oh, got it
thanks for answer!
