### ISSUE TITLE
"mprof plot" with labels does not like spaces in the label

### ISSUE THREAD

**Issue by ianozsvald** [pythonprofilers/memory_profiler#61]
`mprof` can use a context manager to place a label. If the label contains a space e.g. "my label" then a `ValueError` is raised as shown below. If the space is removed (e.g. "my_label") then `mprof plot` displays the label.

It might be easier to make a note in the README stating that spaces aren't allowed if this disturbs your parsing code! Or catching the `ValueError` and hinting that spaces aren't allowed (to give the user a hint).

```
$ mprof plot
Traceback (most recent call last):
  File "/home/ian/workspace/virtualenvs/high_performance_python_orielly/shared_github/raw_code/ian/env/bin/mprof", line 467, in <module>
    actions[get_action()]()
  File "/home/ian/workspace/virtualenvs/high_performance_python_orielly/shared_github/raw_code/ian/env/bin/mprof", line 436, in plot_action
    mprofile = plot_file(filename, index=n, timestamps=timestamps)
  File "/home/ian/workspace/virtualenvs/high_performance_python_orielly/shared_github/raw_code/ian/env/bin/mprof", line 322, in plot_file
    mprofile = read_mprofile_file(filename)
  File "/home/ian/workspace/virtualenvs/high_performance_python_orielly/shared_github/raw_code/ian/env/bin/mprof", line 299, in read_mprofile_file
    ts.append([float(start), float(end),
ValueError: could not convert string to float: list
```

**Comment by Juanlu001** [comment]
This is missing a [SSCCEE](http://www.sscce.org/).
