### ISSUE TITLE
Calling `itervalues` and `iteritems` on dict breaks mprof in Python3

### ISSUE THREAD

**Issue by ZhanruiLiang** [pythonprofilers/memory_profiler#66]
These `iter*` method have been removed and generator become default behaviour in Python 3.

``` sh
% mprof plot
Traceback (most recent call last):
  File "/usr/bin/mprof", line 467, in <module>
    actions[get_action()]()
  File "/usr/bin/mprof", line 436, in plot_action
    mprofile = plot_file(filename, index=n, timestamps=timestamps)
  File "/usr/bin/mprof", line 338, in plot_file
    for values in ts.itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'
```

The Python version is 3.3.3.

**Comment by Juanlu001** [comment]
This is missing an [SSCCEE](http://www.sscce.org/).
